using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Web;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSO2.Echo
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://echo.services.core.carbon.wso2.org/xsd")]
    public partial class SimpleBean
    {

        private string[] a_rField;

        private string[] b_rField;

        private int cField;

        private bool cFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("a_r", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public string[] a_r
        {
            get
            {
                return this.a_rField;
            }
            set
            {
                this.a_rField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("b_r", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 1)]
        public string[] b_r
        {
            get
            {
                return this.b_rField;
            }
            set
            {
                this.b_rField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int c
        {
            get
            {
                return this.cField;
            }
            set
            {
                this.cField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cSpecified
        {
            get
            {
                return this.cFieldSpecified;
            }
            set
            {
                this.cFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://echo.services.core.carbon.wso2.org")]
    public partial class Exception
    {

        private object exception1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Exception", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public object Exception1
        {
            get
            {
                return this.exception1Field;
            }
            set
            {
                this.exception1Field = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "echoStringArrays", WrapperNamespace = "http://echo.services.core.carbon.wso2.org", IsWrapped = true)]
    public partial class echoStringArraysRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://echo.services.core.carbon.wso2.org", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("a", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string[] a;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://echo.services.core.carbon.wso2.org", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("b", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string[] b;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://echo.services.core.carbon.wso2.org", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int c;

        public echoStringArraysRequest()
        {
        }

        public echoStringArraysRequest(string[] a, string[] b, int c)
        {
            this.a = a;
            this.b = b;
            this.c = c;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "echoStringArraysResponse", WrapperNamespace = "http://echo.services.core.carbon.wso2.org", IsWrapped = true)]
    public partial class echoStringArraysResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://echo.services.core.carbon.wso2.org", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public WSO2.Echo.SimpleBean @return;

        public echoStringArraysResponse()
        {
        }

        public echoStringArraysResponse(WSO2.Echo.SimpleBean @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "echoOMElement", WrapperNamespace = "http://echo.services.core.carbon.wso2.org", IsWrapped = true)]
    public partial class echoOMElementRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://echo.services.core.carbon.wso2.org", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public object omEle;

        public echoOMElementRequest()
        {
        }

        public echoOMElementRequest(object omEle)
        {
            this.omEle = omEle;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "echoOMElementResponse", WrapperNamespace = "http://echo.services.core.carbon.wso2.org", IsWrapped = true)]
    public partial class echoOMElementResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://echo.services.core.carbon.wso2.org", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public object @return;

        public echoOMElementResponse()
        {
        }

        public echoOMElementResponse(object @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "echoInt", WrapperNamespace = "http://echo.services.core.carbon.wso2.org", IsWrapped = true)]
    public partial class echoIntRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://echo.services.core.carbon.wso2.org", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @in;

        public echoIntRequest()
        {
        }

        public echoIntRequest(int @in)
        {
            this.@in = @in;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "echoIntResponse", WrapperNamespace = "http://echo.services.core.carbon.wso2.org", IsWrapped = true)]
    public partial class echoIntResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://echo.services.core.carbon.wso2.org", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;

        public echoIntResponse()
        {
        }

        public echoIntResponse(int @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class throwAxisFaultRequest
    {

        public throwAxisFaultRequest()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "throwAxisFaultResponse", WrapperNamespace = "http://echo.services.core.carbon.wso2.org", IsWrapped = true)]
    public partial class throwAxisFaultResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://echo.services.core.carbon.wso2.org", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string @return;

        public throwAxisFaultResponse()
        {
        }

        public throwAxisFaultResponse(string @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "echoString", WrapperNamespace = "http://echo.services.core.carbon.wso2.org", IsWrapped = true)]
    public partial class echoStringRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://echo.services.core.carbon.wso2.org", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string @in;

        public echoStringRequest()
        {
        }

        public echoStringRequest(string @in)
        {
            this.@in = @in;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "echoStringResponse", WrapperNamespace = "http://echo.services.core.carbon.wso2.org", IsWrapped = true)]
    public partial class echoStringResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://echo.services.core.carbon.wso2.org", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string @return;

        public echoStringResponse()
        {
        }

        public echoStringResponse(string @return)
        {
            this.@return = @return;
        }
    }

}
